### ISSUE TITLE
Does not read buffer correctly on slower connections.

### ISSUE THREAD

**Issue by baltuonis** [cgrates/fsock#27]
Sometimes when I connect to remote FreeSWITCH server I get this error

```
Unexpected filter-events reply received: <Content-Length: 1023 Content-Type: text/event-plain
```

From what I've seen in the code it might be that the `readHeaders` is not waiting enought time to receive a complete response and then these responses get returned later for subsequent commands (like CallAPI)

**Comment by baltuonis** [comment]
Any updates?

**Comment by TeoV** [comment]
Hi @baltuonis,

Can you please attach some ngrep in order to reproduce this?

Thanks,
TeoV

**Comment by TeoV** [comment]
Hi @baltuonis,

Do u have any update on this?

Thanks,
TeoV

**Comment by baltuonis** [comment]
Hi @TeoV 
I'll try to get you an ngrep this week.

**Comment by baltuonis** [comment]
Added ngrep output, looks fine...
On this case - the first connect intent failed, the second succeeded.

```
2020/06/24 12:51:43 NewClient: Unexpected filter-events reply received: <Content-Length: 2931
Content-Type: text/event-plain
>
```

[ngrep.txt.zip](https://github.com/cgrates/fsock/files/4826563/ngrep.txt.zip)

**Comment by TeoV** [comment]
Hi @baltuonis,

For beginning sorry it tooks so long to investigate this.
We analyze your ngrep and we found the problem.
This is happening on connect. When we connect the FSock we verify for filters. In case we have we send the filter command to FreeSWITCH and we expect that the FreeSwitch to response ( https://freeswitch.org/confluence/display/FREESWITCH/mod_event_socket ) 
In your case and according to your ngrep( line 619 ) 
```
#
T 127.0.0.1:59442 -> 127.0.0.1:8021 [AP]
filter Event-Name CUSTOM


##
T 127.0.0.1:8021 -> 127.0.0.1:58608 [AP]
Content-Length: 2931
Content-Type: text/event-plain

```
 when the FSock sends the filter command to FreeSWITCH, instead of a response to this it adds in the buffer an event ( with header and body ) and when we try to read from the buffer the response to the filter command which contains we don't find the answer ( Reply-Text: +OK ) and we return an error.

Thanks,
TeoV

**Comment by baltuonis** [comment]
Thanks for your investigation.
So I assume you could include that case in your library code. 
It does not seem that I could do too much on my side without touching internal code
